/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;
import edu.princeton.cs.algs4.Draw;
import ifsc.poo.domain.Grade;

public class App {
    public static void main(String[] args) {
        Draw draw;
        draw = new Draw();
        draw.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        draw.setCanvasSize(1000, 600);
        draw.setXscale(0, 1000);
        draw.setYscale(0, 600);

        for (int i = 0; i < 10; i++){
            for (int j = 0; j < 10; j++){
                draw.square(i * 10, j * 10, 50);
            }
        }

        draw.show();
    }
}
