/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;
import edu.princeton.cs.algs4.Draw;
import ifsc.poo.domain.Grade;
import ifsc.poo.domain.Navio;

public class App {
    Draw draw;

    public App() {
        draw = new Draw();
        draw.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        draw.setCanvasSize(1000, 600);
        draw.setXscale(0, 1000);
        draw.setYscale(0, 600);
    }
    public static void main(String[] args) {
        App app = new App();
        app.draw.show();

        Grade grade  = new Grade();
        grade.desenhar(app.draw);

        Navio navio = new Navio(5, 20, 20, "horizontal", grade);
        navio.desenhar(app.draw);



    }
}
